FROM fedora:21
MAINTAINER Michael Hrivnak <mhrivnak@redhat.com>

ADD python-semantic-version.spec /root/

WORKDIR /root/

RUN yum install -y dnf && yum clean all
RUN dnf -y --setopt deltarpm=0 upgrade && dnf -y install rpm-build make dnf-plugins-core && dnf builddep -y python-semantic-version.spec && dnf clean all

RUN mkdir -p /root/rpmbuild/SOURCES

RUN curl -L https://github.com/rbarrois/python-semanticversion/archive/v2.4.2.tar.gz > /root/rpmbuild/SOURCES/v2.4.2.tar.gz

CMD rpmbuild -bb python-semantic-version.spec
